from __future__ import annotations

import os
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from vd.core.config import COOKIES_DIR


def _browser_getters():
    try:
        import browser_cookie3
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            "browser-cookie3 is required for cookie export. "
            "Install with: python3 -m pip install -r requirements.txt"
        ) from exc

    return {
        "chrome": browser_cookie3.chrome,
        "chromium": browser_cookie3.chromium,
        "brave": browser_cookie3.brave,
        "firefox": browser_cookie3.firefox,
    }


@dataclass
class CookieRow:
    domain: str
    include_subdomains: bool
    path: str
    secure: bool
    expires: int
    name: str
    value: str


def _cookie_rows(jar: Iterable[object]) -> list[CookieRow]:
    rows: list[CookieRow] = []
    for cookie in jar:
        domain = cookie.domain or ""
        include_subdomains = domain.startswith(".")
        rows.append(
            CookieRow(
                domain=domain,
                include_subdomains=include_subdomains,
                path=cookie.path or "/",
                secure=bool(cookie.secure),
                expires=int(cookie.expires or 0),
                name=cookie.name,
                value=cookie.value,
            )
        )
    return rows


def _write_netscape(path: Path, rows: list[CookieRow]) -> None:
    if path.is_symlink():
        raise ValueError('Refusing to export cookies through a symlink')
    for row in rows:
        for value in (row.domain, row.path, row.name, row.value):
            if any(ord(char) < 32 or ord(char) == 127 for char in value):
                raise ValueError('Cookie fields must not contain control characters')
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by VD-uni",
        "",
    ]
    for row in rows:
        include_subdomains = "TRUE" if row.include_subdomains else "FALSE"
        secure = "TRUE" if row.secure else "FALSE"
        lines.append(
            "\t".join(
                [
                    row.domain,
                    include_subdomains,
                    row.path,
                    secure,
                    str(row.expires),
                    row.name,
                    row.value,
                ]
            )
        )
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    descriptor, temporary = tempfile.mkstemp(prefix='.vd-cookies-', dir=path.parent)
    try:
        with os.fdopen(descriptor, 'w', encoding='utf-8') as handle:
            if os.name == 'posix':
                os.fchmod(handle.fileno(), 0o600)
            handle.write("\n".join(lines) + "\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        Path(temporary).unlink(missing_ok=True)


def _normalize_domain(domain: str) -> str:
    try:
        result = domain.strip().lower().removeprefix('.').encode('idna').decode('ascii')
    except UnicodeError as exc:
        raise ValueError('Invalid cookie domain') from exc
    result = result.removeprefix('www.')
    if not result or len(result) > 253 or any(not re.fullmatch(r'[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?', label) for label in result.split('.')):
        raise ValueError('Use a hostname only for cookie export, such as example.com')
    return result


def export_cookies(browser: str, domain: str, output: str | None = None) -> int:
    domain = _normalize_domain(domain)
    getters = _browser_getters()
    if browser not in getters:
        raise ValueError('Unsupported browser for cookie export')
    jar = getters[browser](domain_name=domain)
    # Some browser backends use substring matching. Enforce the DNS boundary.
    rows = [row for row in _cookie_rows(jar)
            if row.domain.lstrip('.').lower() == domain
            or row.domain.lstrip('.').lower().endswith('.' + domain)]
    out_path = Path(output).expanduser() if output else COOKIES_DIR / f"{domain}.txt"
    _write_netscape(out_path, rows)
    print(f"Wrote {len(rows)} cookies to the selected output (owner-only on POSIX).")
    return 0
