from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from vd.core.config import COOKIES_DIR


def _browser_getters():
    try:
        import browser_cookie3
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            "browser-cookie3 is required for cookie export. "
            "Install with: python3 -m pip install -r requirements.txt"
        ) from exc

    return {
        "chrome": browser_cookie3.chrome,
        "chromium": browser_cookie3.chromium,
        "brave": browser_cookie3.brave,
        "firefox": browser_cookie3.firefox,
    }


@dataclass
class CookieRow:
    domain: str
    include_subdomains: bool
    path: str
    secure: bool
    expires: int
    name: str
    value: str


def _cookie_rows(jar: Iterable[object]) -> list[CookieRow]:
    rows: list[CookieRow] = []
    for cookie in jar:
        domain = cookie.domain or ""
        include_subdomains = domain.startswith(".")
        rows.append(
            CookieRow(
                domain=domain,
                include_subdomains=include_subdomains,
                path=cookie.path or "/",
                secure=bool(cookie.secure),
                expires=int(cookie.expires or 0),
                name=cookie.name,
                value=cookie.value,
            )
        )
    return rows


def _write_netscape(path: Path, rows: list[CookieRow]) -> None:
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by VD-uni",
        "",
    ]
    for row in rows:
        include_subdomains = "TRUE" if row.include_subdomains else "FALSE"
        secure = "TRUE" if row.secure else "FALSE"
        lines.append(
            "\t".join(
                [
                    row.domain,
                    include_subdomains,
                    row.path,
                    secure,
                    str(row.expires),
                    row.name,
                    row.value,
                ]
            )
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def export_cookies(browser: str, domain: str, output: str | None = None) -> int:
    COOKIES_DIR.mkdir(parents=True, exist_ok=True)

    getters = _browser_getters()
    getter = getters[browser]
    jar = getter(domain_name=domain)
    rows = _cookie_rows(jar)

    out_path = Path(output) if output else COOKIES_DIR / f"{domain}.txt"
    _write_netscape(out_path, rows)
    print(f"Wrote {len(rows)} cookies to {out_path}")
    return 0
